# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.provider "virtualbox"
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "bacnet-jre"
  config.vm.synced_folder "../mnt", "/mnt"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.cpus = 1
    vb.memory = "256"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get upgrade -y
    apt-get install -y vim curl telnet netcat nmap tcpdump net-tools
    apt-get install -y linux-image-$(uname -r) linux-headers-$(uname -r)
    # curl -OL https://download.virtualbox.org/virtualbox/6.0.14/VBoxGuestAdditions_6.0.14.iso
    # mkdir /media/iso
    # mount -o loop -t iso9660 VBoxGuestAdditions_6.0.14.iso /media/iso
    # /media/iso/VBoxLinuxAdditions.run
  SHELL

  config.vm.define "bacnet1" do |bacnet1|
    bacnet1.vm.hostname = "bacnet-jre"
    bacnet1.vm.network "private_network", ip: "10.10.14.13"
    bacnet1.vm.provider "virtualbox" do |vb|
      vb.name = "bacnet1"
    end

    bacnet1.vm.provision "shell", inline: <<-SHELL
      apt-get install -y openjdk-8-jre-headless
    SHELL
  end

  config.vm.define "bacnet2" do |bacnet2|
    bacnet2.vm.hostname = "bacnet-py"
    bacnet2.vm.network "private_network", ip: "10.10.14.14"
    bacnet2.vm.provider "virtualbox" do |vb|
      vb.name = "bacnet2"
    end

    bacnet2.vm.provision "shell", inline: <<-SHELL
      apt-get install -y git python3-pip
      git clone https://github.com/JoelBender/bacpypes.git
      cd bacpypes && pip3 install .
      sed -e 's#192.168.210.64/24#10.10.14.14/24#g' BACpypes~.ini > BACpypes.ini
    SHELL
  end

end
